### ISSUE TITLE
 Error: Invalid dependency type requested: alias

### ISSUE THREAD

**Issue by ahmad-crossplatform** [enactjs/templates#16]
after installed Template "webostv". 
I tried to create an app using 
```enact create -t webostv MyApp```

but I received an error saying ` Error: Invalid dependency type requested: alias`

**Comment by sugardave** [comment]
What version of Enact CLI are you using?  I just tried this and got the hello world app with `@enact/webos` as a dependency.

I have:
`npm 6.9.0`
`enact 2.5.1`

edit: It's probably this dependency `"ilib": "npm:ilib-webos-tv@^14.2.0-webostv1"` and you'll need a version of `npm` that supports aliases

**Comment by JayCanuck** [comment]
I believe @sugardave is correct. The `webostv` template is special in that it uses an NPM alias to override `ilib` with the webos variant `ilib-webos-tv`. The NPM alias feature requires NPM >=6.9.0. Updating to the latest NPM release will correct this error for you.

**Comment by webOS101** [comment]
@ahmad-crossplatform Did upgrading your `npm` resolve this issue?  Alternately, you can change the version of `ilib` to use the standard ilib install instead of the webOS TV version:

```
  "ilib": "^14.2.0",
```

**Comment by ahmad-crossplatform** [comment]
Hello guys  , I am not really sure what ilib is to be honest , but i think now ,as you guys said, it has been fixed after updating npm and it works .
